GET http://localhost:4000/me/top/genres
Cookie: authToken=BQCrybM21xnubgCk7hPjS3lz7JLbAIs7w1NlVMLnF634FTtIS34mknziIfL3WqTfTq3IN5y-GTdxoKXuThHEN4aFoLMRgbiGvgv3iUqetoOZGBUfwDjMT69w2uPW3Dmu7LZvTkIhcOkzsqyFr6SHWgKsw2cobtezbUS26IK0_VQi67MLYaNMQ00TEzyJpYVU-1NgG5JdHIx7M-HcddiQbo9pjx7IFV44