GET http://localhost:4000/me/top/genres
Cookie: authToken=BQBa3ASCXUEjT5kfFJQlkdjGVFoGCs_MavR9TBXvsqmjAzxvU_F4wP5LaaY4gLU37OMIYbfvQ8sgEYdcBM-zbQCXboIADCDWWTpLmAYQUkA4uqO6l82UmamAB6NRz8_K1847xAg4TSg5AahckA9Gwnp_YldIxadX6kXgpF0QOthikwDFr7hXqAm43MBM6P12LPoqopfG1UgN0cp9gtiV8z-4vx532isC